database: etcdv3
test_name: 01-etcdv3

peer_ips:
    - 10.240.0.13
    - 10.240.0.14
    - 10.240.0.15

agent_port: 3500
database_port: 2379

log: control.log
data_size_summary: data-size-summary.csv
data_latency_distribution_summary: data-latency-distribution-summary.csv
data_latency_distribution_percentile: data-latency-distribution-percentile.csv
data_latency_distribution_all: data-latency-distribution-all.csv
data_latency_throughput_timeseries: data-latency-throughput-timeseries.csv
data_latency_by_key_number: data-latency-by-key-number.csv

# client machine's system metrics
client_system_metrics: client-system-metrics.csv

# start database by sending RPC calls to agents
step1:
    skip_start_database: false
    etcd_snap_count: 100000
    etcd_quota_size_bytes: 8000000000
    zookeeper_snap_count: 100000
    zookeeper_max_client_connections: 5000

# start benchmark
step2:
    skip_stress_database: false
    bench_type: write
    stale_read: true
    connections: 1
    clients: 1
    # if specified, connections, clients are overwritten
    connections_clients: [1, 3, 5, 10, 50, 100, 500, 700, 1000]
    key_size: 256
    value_size: 1024
    total_requests: 100000
    requests_per_second: 100

# after benchmark
step3:
    action: stop

# upload logs
step4:
    upload_logs: true
    google_cloud_project_name: etcd-development
    google_cloud_storage_key_path: $HOME/gcloud-key.json
    google_cloud_storage_bucket_name: dbtester-results
    google_cloud_storage_sub_directory: 2017Q1-02-etcd-zookeeper-consul/01-write-1M-keys-client-variable
