database: etcdv3
test_name: 01-etcdv3

google_cloud_project_name: etcd-development
google_cloud_storage_key_path: $HOME/gcloud-key.json
google_cloud_storage_bucket_name: dbtester-results
google_cloud_storage_sub_directory: 2016041501 

peer_ips:
    - 10.240.0.13
    - 10.240.0.14
    - 10.240.0.15

agent_port: 3500
database_port: 2379

log: control.log
data_latency_all: data-latency-all.csv
data_latency_distribution_summary: data-latency-distribution-summary.csv
data_latency_distribution_percentile: data-latency-distribution-percentile.csv
data_latency_distribution_all: data-latency-distribution-all.csv
data_latency_throughput_timeseries: data-latency-throughput-timeseries.csv

# start database by sending RPC calls to agents
step1:
    skip_start_database: false
    etcd_snap_count: 100000
    zookeeper_snap_count: 100000
    zookeeper_max_client_connections: 5000

# start benchmark
step2:
    skip_stress_database: false
    bench_type: write
    stale_read: true
    connections: 100
    clients: 100
    connections_clients_delta: 100
    connections_clients_max: 2000 # if not 0, increase clients per 100K requests (only for writes)
    key_size: 8
    same_key: true
    value_size: 256
    total_requests: 2000000
    requests_per_second: 100

# after benchmark
step3:
    action: stop
